### PR TITLE
[gauravlall, shanmukht]: Refactored vagrant structure to support multipe flavor of Linux. Here we tested on centos7 & redhat7.

### PR DESCRIPTION
**Pull request by shanmukht**

### CODE REVIEW

**Comment by shanmukht** [comment]
Updated the code as per Gaurav's review.

**Comment by gauravlall** [comment]
@shanmukht Can you please resolve the conflicts?

**Comment by shanmukht** [comment]
@gauravlall conflicts resolved.

**Comment by shanmukht** [comment]
@gauravlall conflicts resolved.

**Pull request closed without merging**
